name: Xcode Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy: 
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest']
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        xcodebuild clean -project covid19-sounds.xcodeproj -scheme covid19-sounds -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env:
        destination: ${{ matrix.destination }}
